### ISSUE TITLE
Build Error when installing the library

### ISSUE THREAD

**Issue by marlyo69** [runette/ngx-leaflet-sidebar#10]
Hi,
i am trying to import this library into my project, which is running with ngx-leaflet and angular 13
i installed it with the 'npm install @runette/ngx-leaflet-sidebar' but just after when i tried to build my project (npm run build) i got this error : 
./node_modules/@runette/ngx-leaflet-sidebar/fesm2015/runette-ngx-leaflet-sidebar.js:4:0-67 - Error: Module not found: Error: Can't resolve 'node_modules/leaflet-sidebar-v2/js/leaflet-sidebar.min.js' in 'C:\User
s\jbiloum\workspace\ekrs-frontend\node_modules\@runette\ngx-leaflet-sidebar\fesm2015'

here is a snapshot of my package.json : 
    "@angular/animations": "~13.3.2",
    "@angular/cdk": "^13.3.2",
    "@angular/common": "~13.3.2",
    "@angular/compiler": "~13.3.2",
    "@angular/core": "~13.3.2",
    "@angular/flex-layout": "^13.0.0-beta.38",
    "@angular/forms": "~13.3.2",
    "@angular/material": "^13.3.2",
    "@angular/material-moment-adapter": "^13.2.0",
    "@angular/platform-browser": "~13.3.2",
    "@angular/platform-browser-dynamic": "~13.3.2",
    "@angular/router": "~13.3.2",
    "@asymmetrik/ngx-leaflet": "^13.0.2",
    "@indigo-multi/authentication-oidc": "^2.0.1",
    "@indigo-multi/fonts": "2.0.0",
    "@indigo-multi/http": "2.0.0",
    "@indigo-multi/icons": "2.3.0",
    "@indigo-multi/logging": "2.0.0",
    "@indigo-multi/server-sent-event": "^1.0.0",
    "@indigo-multi/tracker": "^2.0.1",
    "@indigo-web/diagnostic": "2.0.0",
    "@indigo-web/material": "2.3.0",
    "@ngx-translate/core": "13.0.0",
    "@ngx-translate/http-loader": "6.0.0",
    "@runette/ngx-leaflet-sidebar": "^1.0.8",
    "@tinymce/tinymce-angular": "^4.2.2",
    "@types/leaflet": "^1.7.5",
    "angular2-highcharts": "^0.5.5",
    "angular2-uuid": "^1.1.1",
    "chart.js": "^3.7.1",
    "core-js": "^2.5.4",
    "highcharts": "^11.0.1",
    "highlight.js": "^10.5.0",
    "leaflet": "^1.7.1",

any hint would be appreciated.

**Comment by marlyo69** [comment]
i tried to see if the file was existing, so in the runette-ngx-leaflet-sidebar.js file, there is an import in line 4 : 
import 'node_modules/leaflet-sidebar-v2/js/leaflet-sidebar.min.js'; i followed the link and the file does exist, i can't explain why i get this error.

**Comment by runette** [comment]
That error usually means that there is a problem with the dependencies - a constant pain with npm.

try installing leaflet-sidebar-v2 explicitly (i.e. ```npm install leaflet-sidebar-v2```)

**Comment by marlyo69** [comment]
i have just imported explicitly leaflet-sidebar-v2 before ngx-leaflet-sidebar and the issue is still present. the import statement in your library ('import node_modules/...) is still failing. i don't understand why you import sidebar-v2 that way and not just as a module.

**Comment by runette** [comment]
Lets be clear - you are saying that you have leaflet-sidebar-v2 installed but you do NOT have 'node_modules/leaflet-sidebar-v2/js/leaflet-sidebar.min.js ?

Seems unlikely.

You might reflect on the fact that leaflet-sidebar-v2 is not a module - it is a leaflet extension script

**Comment by marlyo69** [comment]
no, the file exists, what i don't understand is why in your library file, it is not found.
Module not found: Error: Can't resolve 'node_modules/leaflet
-sidebar-v2/js/leaflet-sidebar.min.js' in 'C:\Users\jbiloum\workspace\ekrs-front
end\node_modules\@runette\ngx-leaflet-sidebar\fesm2015'.
that being said, i must say it's the first time that i see a javascript file import in an angular component. normaly i would put it in the scripts array in angular.json file. (i also done that but with no success)

**Comment by runette** [comment]
There is nothing unusual about adding js in that way and adds them in a more encapsulated way than the global addition in angular-json (i.e. in the component). It is only appropriate for old code - but then Leaflet is old code.

I cannot help further - It works for me and other people. It is an artefact of your node-modules - if it was me I would delete that and start again although I would never suggest that as a solution to anyone.

As a side note - I have actually transferred all of my projects to either OpenLayers or MapLibrte-gl as being more modern, more Angular aware and also because of Vector Tiles! I am actually planning to archive this library since I am not sure we should be using Leaflet anymore.
