### ISSUE TITLE
doesn't work with Angular 13

### ISSUE THREAD

**Issue by marlyo69** [runette/ngx-leaflet-sidebar#13]
Hi,
i am trying to import this library into my project, which is running with ngx-leaflet and angular 13
i installed it with the 'npm install @runette/ngx-leaflet-sidebar' but just after when i tried to build my project (npm run build) i got this error :
./node_modules/@runette/ngx-leaflet-sidebar/fesm2015/runette-ngx-leaflet-sidebar.js:4:0-67 - Error: Module not found: Error: Can't resolve 'node_modules/leaflet-sidebar-v2/js/leaflet-sidebar.min.js' in 'C:\User
s\jbiloum\workspace\ekrs-frontend\node_modules@runette\ngx-leaflet-sidebar\fesm2015'

here is a snapshot of my package.json :
"@angular/animations": "~13.3.2",
"@angular/cdk": "^13.3.2",
"@angular/common": "~13.3.2",
"@angular/compiler": "~13.3.2",
"@angular/core": "~13.3.2",
"@angular/flex-layout": "^13.0.0-beta.38",
"@angular/forms": "~13.3.2",
"@angular/material": "^13.3.2",
"@angular/material-moment-adapter": "^13.2.0",
"@angular/platform-browser": "~13.3.2",
"@angular/platform-browser-dynamic": "~13.3.2",
"@angular/router": "~13.3.2",
"@asymmetrik/ngx-leaflet": "^13.0.2",
"@indigo-multi/authentication-oidc": "^2.0.1",
"@indigo-multi/fonts": "2.0.0",
"@indigo-multi/http": "2.0.0",
"@indigo-multi/icons": "2.3.0",
"@indigo-multi/logging": "2.0.0",
"@indigo-multi/server-sent-event": "^1.0.0",
"@indigo-multi/tracker": "^2.0.1",
"@indigo-web/diagnostic": "2.0.0",
"@indigo-web/material": "2.3.0",
"@ngx-translate/core": "13.0.0",
"@ngx-translate/http-loader": "6.0.0",
"@runette/ngx-leaflet-sidebar": "^1.0.8",
"@tinymce/tinymce-angular": "^4.2.2",
"@types/leaflet": "^1.7.5",
"angular2-highcharts": "^0.5.5",
"angular2-uuid": "^1.1.1",
"chart.js": "^3.7.1",
"core-js": "^2.5.4",
"highcharts": "^11.0.1",
"highlight.js": "^10.5.0",
"leaflet": "^1.7.1",

any hint would be appreciated.

**Comment by runette** [comment]
duplicate
