### ISSUE TITLE
Angular 12 not working

### ISSUE THREAD

**Issue by giancafigueroa** [runette/ngx-leaflet-sidebar#4]
Div sidebar not position into map

![image](https://user-images.githubusercontent.com/12590012/159056111-1035ee54-2542-4b14-b5ab-b1058915190d.png)

**Comment by runette** [comment]
I think that the latest version I have tested it with was 10 or 11. 

Please feel welcome to diagnose the problem and create a PR - I am in the field at the moment and wont have the conectectivty or the compute power to create and test any solution for about 1 month

**Comment by pigsi** [comment]
Hi, i have a more basic problem with Angular 12. After package instalation i get an error during build " Module '"leaflet"' has no exported member 'SidebarOptions'" ,  versions in package.json are : 
 "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@asymmetrik/ngx-leaflet": "^8.1.0",
    "@asymmetrik/ngx-leaflet-markercluster": "^13.0.1",
    "@runette/ngx-leaflet-fullscreen": "^1.0.5",
    "@runette/ngx-leaflet-sidebar": "^1.0.3",
    "@types/leaflet.markercluster": "^1.4.6",
    "leaflet": "^1.7.1",
    "leaflet.markercluster": "^1.5.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"

can you help ?

**Comment by runette** [comment]
`SidebarOptions` is provided by the ` "leaflet-sidebar-v2": "^3.2.2"` package  - and so should be there if that package is loaded.

I am now back in my home country and my office - so I can try to take a look and see if it is an ngx12 issue

**Comment by runette** [comment]
The `SidebarOptions` problem is because you have not included the line

```
/// <reference types='leaflet-sidebar-v2' />
```

At the top of the relevant .ts file. This is mentioned in the docs  - but I probably have to make it clearer.

I did find that the current npm package is out of date and needs to be updated with the correct versions. I will do that now.

**Comment by runette** [comment]
Release 1.0.4 will be built correct;y for versions of Angular 12+
